import { pool } from './database.js'

const sampleEvents = [
    ['Echo Lounge', 'Indie Discovery Night', '2026-11-07', '19:00', '/indie.jpg'],
    ['Echo Lounge', 'Local Artists Showcase', '2026-12-12', '20:00', '/local.jpg'],
    ['Echo Lounge', 'Winter Sound Sessions', '2027-01-23', '19:30', '/winter.jpg'],
    ['House of Blues', 'Blues and Roots Live', '2026-11-14', '19:00', '/blues.jpg'],
    ['House of Blues', 'Saturday Night Showcase', '2026-12-19', '20:00', '/showcase.jpg'],
    ['House of Blues', 'New Year Music Celebration', '2027-01-30', '19:30', '/newYear.jpg'],
    ['Pavilion', 'Autumn Live in the Park', '2026-11-21', '18:00', '/autumn.jpg'],
    ['Pavilion', 'Community Music Festival', '2026-12-26', '17:00', '/community.jpg'],
    ['Pavilion', 'Winter Open-Air Concert', '2027-02-06', '18:30', '/open.jpg'],
    ['American Airlines Center', 'Arena Concert Night', '2026-11-28', '19:30', '/arena.jpg'],
    ['American Airlines Center', 'Holiday Headliner Live', '2027-01-09', '20:00', '/holiday.jpg'],
    ['American Airlines Center', 'New Season Live Showcase', '2027-02-13', '19:30', '/live.jpg']
]

const setupDatabase = async () => {
    const client = await pool.connect()

    try {
        await client.query('BEGIN')

        await client.query(`
            CREATE TABLE IF NOT EXISTS locations (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT NOT NULL UNIQUE,
                address TEXT,
                city TEXT,
                state TEXT,
                zip TEXT,
                image TEXT
            )
        `)

        await client.query(`
            CREATE TABLE IF NOT EXISTS events (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                title TEXT NOT NULL,
                date DATE,
                time TIME,
                image TEXT,
                location_id INTEGER NOT NULL REFERENCES locations(id) ON DELETE CASCADE
            )
        `)

        await client.query(`
            INSERT INTO locations (name)
            VALUES
                ('Echo Lounge'),
                ('House of Blues'),
                ('Pavilion'),
                ('American Airlines Center')
            ON CONFLICT (name) DO NOTHING
        `)

        for (const [locationName, title, date, time, image] of sampleEvents) {
            const updateValues = [title, date, image, locationName]
            const result = await client.query(`
                UPDATE events
                SET image = $3
                WHERE title = $1
                  AND date = $2
                  AND location_id = (SELECT id FROM locations WHERE name = $4)
            `, updateValues)

            if (result.rowCount === 0) {
                await client.query(`
                    INSERT INTO events (title, date, time, image, location_id)
                    SELECT $1, $2, $3, $4, id
                    FROM locations
                    WHERE name = $5
                `, [title, date, time, image, locationName])
            }
        }

        await client.query('COMMIT')
        console.log('Database tables and sample events are ready; missing default rows were added.')
    } catch (error) {
        await client.query('ROLLBACK')
        throw error
    } finally {
        client.release()
        await pool.end()
    }
}

setupDatabase().catch((error) => {
    console.error('Database setup failed:', error.message)
    process.exitCode = 1
})
